LPK-3470 Fileupload exception fix candidate.
The production logs are filled with errors related to fileupload:
Error: cannot call methods on fileupload prior to initialization;
attempted to call method 'destroy'. The root cause is still a mystery,
but let's see if we have found the origin of the exception.